### ISSUE TITLE
v17 is tagged suspiciously

### ISSUE THREAD

**Issue by dcfsc** [whelk-io/maven-settings-xml-action#110]
I tried to use the code in the example

    - name: "Setup Maven"
      uses: whelk-io/maven-settings-xml-action@v17

I got this message

```
Failed to resolve action download info. Error: Unable to resolve action `whelk-io/maven-settings-xml-action@v17`, unable to find version `v17`
Retrying in 15.206 seconds
Failed to resolve action download info. Error: Unable to resolve action `whelk-io/maven-settings-xml-action@v17`, unable to find version `v17`
Retrying in 25.688 seconds
Error: Unable to resolve action `whelk-io/maven-settings-xml-action@v17`, unable to find version `v17`
```
I changed the version to 

      - name: "Setup Maven"
        uses: whelk-io/maven-settings-xml-action@17

Now it downloads:

    Download action repository 'whelk-io/maven-settings-xml-action@17'

Is the new tag named incorrectly, or did the usage change on purpose?

tag: https://github.com/whelk-io/maven-settings-xml-action/releases/tag/17

**Comment by zteater** [comment]
@dcfsc oops forgot the `v` when tagging the release. Should be good now.

**Comment by zteater** [comment]
@dcfsc also your changes for the default location on the settings.xml looks really promising, please PR back to the root once you've flushed it out.

**Comment by dcfsc** [comment]
I see you already implemented `output_file`. Good show, sorry I forgot... I will revert back to here!
