### ISSUE TITLE
Node.js 12 Upgrade to Node.js16

### ISSUE THREAD

**Issue by santiagonieto** [whelk-io/maven-settings-xml-action#148]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: whelk-io/maven-settings-xml-action

**Comment by benbenw** [comment]
@santiagonieto this was done a few month ago in cee7c2f4ed9d999f06d307272d2a3ac6e5734fc1

@zteater Could you do a v21 release ? (thanx for your action by the way)

**Comment by zteater** [comment]
@santiagonieto Added to version 21
