### ISSUE TITLE
Node 16-warning from GHA-workflow

### ISSUE THREAD

**Issue by avoldsund** [whelk-io/maven-settings-xml-action#164]
While running my Github Actions-workflow I get this warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: whelk-io/maven-settings-xml-action@7c60eb95b2d5ec18f2e0e29f34c9ed69475e7a96. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Are there any plans to upgrade from node 16 to 20?

**Comment by zteater** [comment]
Fixed with [v22](https://github.com/whelk-io/maven-settings-xml-action/releases/tag/v22)
