### ISSUE TITLE
Add properties config

### ISSUE THREAD

**Issue by zteater** [whelk-io/maven-settings-xml-action#6]

**Comment by zteater** [comment]
See http://maven.apache.org/settings.html#properties for context on how properties are used.

**Comment by TuomasKiviaho** [comment]
![image](https://user-images.githubusercontent.com/886635/113258228-58795200-92d4-11eb-8a07-5928fe902203.png)

Properties would indeed be useful in controlling the distribution management

**Comment by zteater** [comment]
@TuomasKiviaho I believe the properties you're describing are part of the `<profile>`, which is already supported: https://github.com/whelk-io/maven-settings-xml-action#full-usage

Looks like this issue is no longer needed.
