### ISSUE TITLE
Setting Local Repository

### ISSUE THREAD

**Issue by Bharani-Schawk** [whelk-io/maven-settings-xml-action#67]
Hi,
Im downloading the entire m2 folder from my server into the runner. i want to set the local repository say '/tmp/m2'. will it be possible to set local folder as repo so that maven wont download the dependencies from maven central repo?

thanks,
Bharani.

**Comment by zteater** [comment]
@Bharani-Schawk you'll want to use Maven's offline-mode for that. Baeldung has some good information on this: https://www.baeldung.com/maven-offline

But basically you need to run your mvn command with `-o`. 

Example:  `mvn package -o`
