### ISSUE TITLE
Add flag to include maven repo, true by default

### ISSUE THREAD

**Issue by zteater** [whelk-io/maven-settings-xml-action#7]

**Comment by jason-edstrom** [comment]
Is this related to the sonatype snapshot repo for open source? `ossrh`?

**Comment by zteater** [comment]
@jason-edstrom  actually, this is to toggle on/off the default maven central repo:

By default, all `settings.xml` gets this from the template:

````
                <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2</url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
````

So presumably a boolean could be added to toggle this on or off. Or, some other mechanism to run in "default" mode. I would imagine default mode you get the standard maven central repo within the github profile, e.g.
