### ISSUE TITLE
Support deep XML configs

### ISSUE THREAD

**Issue by FalconerTC** [whelk-io/maven-settings-xml-action#88]
The following config

```
      - name: Maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: |
            [
              {
                "id": "some-id",
                "username": "${env.USER}",
                "password": "${env.PASS}",
                "configuration": {
                  "httpConfiguration": {
                    "all": {
                      "usePreemptive": "true"
                    }
                  }
                }
              }
            ]
```

Will result in
```
  <servers><server><id>some-id</id><username>${env.USER}</username><password>${env.PASS}</password><configuration>[object Object]</configuration></server></servers>
```

It would be nice to be able to configure deep settings, without having to just embed XML as a string for anything deeper than 2 levels.

**Comment by zteater** [comment]
@FalconerTC updated the `server` parsing to accept any json from `configuration` and parse to xml. The spec for what can go into that element seems to be wide open on the Maven side. 

Also, noticed we didn't have full support for all the fields in `server` element so added `privateKey`, `passphrase`, `filePermissions`, and `directoryPermissions` in case you need those too.

**Comment by zteater** [comment]
@FalconerTC this has been release on v16. Thank you for the feedback!
