### ISSUE TITLE
Is there any ways to specify the activeProfile instead of using github.

### ISSUE THREAD

**Issue by xw185019-ncr** [whelk-io/maven-settings-xml-action#98]
Hi, 

  Just wondering whether it has any ways to specify the activeProfile other than "github", 

regards
Dawnseeker

**Comment by zteater** [comment]
@xw185019-ncr  not currently, but it can be added. For now, you can add a new profile and then reference it with `mvn -P`.

**Comment by zteater** [comment]
@xw185019-ncr added to release 17: https://github.com/whelk-io/maven-settings-xml-action/releases/tag/17
